### ISSUE TITLE
Gallery画廊效果可以展示多个view吗？

### ISSUE THREAD

**Issue by shihchieh-ma** [ymex/banner#1]
您好，请教一个问题，我看demo中Gallery画廊里每次只能看到三个图片，有个需求比如我想看到5个或者更多的话有相应设置方法吗？或者我该在哪里修改些什么呢？谢谢。

**Comment by ymex** [comment]
该库不支持， 你可以通过RecyclerView 和 SnapHelper 自定义实现。

**Comment by ymex** [comment]
@Marlborn 该库不支持， 你可以通过RecyclerView 和 SnapHelper 自定义实现。

**Comment by shihchieh-ma** [comment]
好的，感谢您的回复。

**Comment by ymex** [comment]
r
