### ISSUE TITLE
Gallery画廊无法滑动的bug

### ISSUE THREAD

**Issue by AdobeSolo** [ymex/banner#2]
你好，最近在使用你的这个库时发现了一个bug,具体详情如下，

在gallery画廊中，通过手动滑动画廊，一直滑动，大约循环个10来次左右会出现view卡死，无法滑动的问题。

**Comment by AdobeSolo** [comment]
qq745004937 如果需要我复现问题的话，可以联系我！

**Comment by ymex** [comment]
glide 冲突，设置banner.createView(CreateViewCaller.build())或自定义布局 替代默认的banner 布局
