### ISSUE TITLE
Gallery模式循环后切换到第一页 右边的图像会闪一下再显示

### ISSUE THREAD

**Issue by shen5818** [ymex/banner#4]
Gallery模式循环后切换到第一页 右边的图像会闪一下再显示 ，这个有办法解决吗？

**Comment by ymex** [comment]
暂时没有好的解决方案。

**Comment by ymex** [comment]
> Gallery模式循环后切换到第一页 右边的图像会闪一下再显示 ，这个有办法解决吗？

暂时没有好的方案。
