### ISSUE TITLE
V1.6.7报错

### ISSUE THREAD

**Issue by manburenshenglu** [ymex/banner#5]
错误信息：java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.support.v7.widget.AppCompatImageView
位置：setOnClickBannerListener(new OnClickBannerListener<AppCompatImageView, BanneModel>()

**Comment by manburenshenglu** [comment]
V1.6.6没有该问题，但是V1.6.6当只有两张图片时无法滚动

**Comment by ymex** [comment]
@manburenshenglu 

1.6.7 默认构建的banner 页，使用了FrameLayout 对 ImageView 进行了包裹（解决使用glide时对tag 重用问题）。所以 `OnClickBannerListener<AppCompatImageView, BanneModel>` 的泛型类型`AppCompatImageView`, 改成其匹配类型`FrameLayout`或`View`。 这点当初没有考虑到对之前版本兼容引起的。

参考这里的代码：[OnClickBannerListener](https://github.com/ymex/banner/blob/master/sample/src/main/java/com/example/banner/DefaultBannerActivity.java)

**Comment by ymex** [comment]
> V1.6.6没有该问题，但是V1.6.6当只有两张图片时无法滚动


[ 是这样子的 ](https://github.com/ymex/banner/issues/3) ， 下版本增加自定义这个参数并对click兼容。

**Comment by manburenshenglu** [comment]
了解，谢谢
